#!/bin/bash
# youtube-stream server
# chkconfig: - 85 15

home=/usr/local/youtube-stream
pyhome=/usr/local/bin

get_pid () {
	local pid=$(ps aux | grep /youtube-stream/server.py | grep -v grep | awk '{print $2}')
	echo $pid	
}

start() {
	pid=$(get_pid)
	if [ -z $pid ]; then
		echo -e "starting youtube-stream server\n"
		$pyhome/python2.7 -u $home/server.py >>$home/access.log 2>&1 &
	else
		echo -e "youtube-stream is already running with pid=$pid\n"
	fi	
}


stop() {
	pid=$(get_pid)
	if [ -z $pid ]; then
		echo -e "youtube-stream is not running\n"
	else
		echo -e "killing server process pid=$pid...\n"
		kill -9 $pid
	fi	
}


case "$1" in 
	start) 
		start
		;;
	stop)
		stop
		;; 
	restart)
		stop
		start
		;;
	*)
		echo "Usage: service yt-stream start|stop|restart"
		exit 1
esac


